use_frameworks!

abstract_target 'Abstract_Example' do
  pod 'RxCoreRedux', :path => '../'
  pod 'RxCoreBase', :path => '../'
  pod 'RxCoreBaseExtension', :path => '../'
  pod 'RxCoreList', :path => '../'
  pod 'RxCoreRequest', :path => '../'
  pod 'RxCoreRemoteRepository', :path => '../'
  pod 'RxCoreRepository', :path => '../'
  pod 'RxCoreAPNS', :path => '../'
  pod 'RxCocoa'
  pod 'SwiftDate'
  pod 'Toaster'
  pod 'Valet'
  
  target 'Example' do
  end

  target 'Example_Realm' do
    pod 'RxCoreRealm', :path => '../'
  end
  
  target 'Example_CoreData' do
    pod 'RxCoreCoreData', :path => '../'
  end
end
